//! # Grove Compiler
//!
//! A tree-based compiler for the SuperInstance ecosystem.
//!
//! The compiler operates in four seasonal passes:
//! - **Spring** ([`spring`]) — Parsing: tokens germinate into AST trees
//! - **Summer** ([`summer`]) — Type checking: ecological niche verification
//! - **Autumn** ([`autumn`]) — Optimization: pruning, folding, dead code elimination
//! - **Winter** ([`winter`]) — Code generation: harvesting trees into bytecode
//!
//! ## Quick Start
//!
//! ```rust
//! use grove_compiler::{spring, autumn, winter};
//!
//! let source = "let x = 2 + 3 x * 4";
//! let parsed = spring::parse(source);
//! if let Some(expr) = parsed.expr {
//!     let optimized = autumn::optimize(&expr);
//!     let compiler = winter::Compiler::new().compile(&optimized);
//!     println!("Bytecode: {:?}", compiler.bytecode());
//! }
//! ```

pub mod ast;
pub mod autumn;
pub mod spring;
pub mod summer;
pub mod token;
pub mod winter;

pub use ast::{BinOpKind, Diagnostic, Expr, Stmt, Type, TypedExpr, UnaryKind};
pub use autumn::optimize;
pub use spring::parse;
pub use summer::typecheck;
pub use token::{Token, tokenize};
pub use winter::{Bytecode, Compiler};

/// Run the full compilation pipeline: source → bytecode.
///
/// This is the end-to-end journey through all four seasons.
pub fn compile(source: &str) -> CompilationResult {
    // Spring: parse
    let parse_result = spring::parse(source);
    let diagnostics = parse_result.diagnostics.clone();

    let Some(expr) = parse_result.expr else {
        return CompilationResult {
            bytecode: Vec::new(),
            constants: Vec::new(),
            diagnostics,
            success: false,
        };
    };

    // Summer: type check (warnings only, don't block compilation)
    let _type_result = summer::typecheck(&expr);

    // Autumn: optimize
    let optimized = autumn::optimize(&expr);

    // Winter: code generation
    let compiler = winter::Compiler::new().compile(&optimized);

    CompilationResult {
        bytecode: compiler.bytecode,
        constants: compiler.constants,
        diagnostics,
        success: true,
    }
}

/// The result of a full compilation pass.
#[derive(Debug, Clone)]
pub struct CompilationResult {
    /// Generated bytecode.
    pub bytecode: Vec<Bytecode>,
    /// Numeric constants collected during compilation.
    pub constants: Vec<f64>,
    /// Any diagnostics accumulated during compilation.
    pub diagnostics: Vec<Diagnostic>,
    /// Whether compilation succeeded.
    pub success: bool,
}

#[cfg(test)]
mod integration_tests {
    use super::*;

    #[test]
    fn full_pipeline_arithmetic() {
        let result = compile("2 + 3 * 4");
        assert!(result.success);
        assert!(result.diagnostics.is_empty());
        assert!(!result.bytecode.is_empty());
    }

    #[test]
    fn full_pipeline_let_binding() {
        let result = compile("let x = 10 x + 5");
        assert!(result.success);
    }

    #[test]
    fn full_pipeline_ternary() {
        let result = compile("1 ? 42 : 99");
        assert!(result.success);
    }

    #[test]
    fn full_pipeline_optimized() {
        // After optimization, (2+3) should fold to 5
        let result = compile("2 + 3");
        assert!(result.success);
        // Should be just: Push(5.0), Halt (constant folded)
        assert_eq!(result.bytecode[0], Bytecode::Push(5.0));
    }

    #[test]
    fn full_pipeline_if_else() {
        let result = compile("if 1 42 else 99");
        assert!(result.success);
    }

    #[test]
    fn full_pipeline_complex() {
        let result = compile("let x = 2 + 3 let y = x * 4 y - 1");
        assert!(result.success);
    }

    #[test]
    fn empty_source() {
        let result = compile("");
        assert!(result.success);
    }
}
